version: 2

jobs:
  osx:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: |
            python --version
            python -m pip --version
            python -m pip install -q --user --ignore-installed --upgrade virtualenv
            python -m virtualenv -p python venv
            venv/bin/python -m pip install -r requirements-dev.txt
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

  linux:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: |
            python --version
            python -m pip --version
            python -m pip install -q --user --ignore-installed --upgrade virtualenv
            python -m virtualenv -p python venv
            venv/bin/python -m pip install -r requirements-dev.txt
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

workflows:
  version: 2
  all-tests:
    jobs:
      - linux
      - osx
