version: 2

jobs:
  osx-python2:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: |
            echo 'export PYTHON=python2' >> $BASH_ENV
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

  osx-python3:
    macos:
      xcode: "10.0.0"
    steps:
      - checkout

      - run:
          name: Prepare the environment.
          command: |
            echo 'export PYTHON=python3' >> $BASH_ENV
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

  linux-python2:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: |
            echo 'export PYTHON=python2' >> $BASH_ENV
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

  linux-python3:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Prepare the environment.
          command: |
            echo 'export PYTHON=python3' >> $BASH_ENV
            bash .circleci/prepare.sh
      - run:
          name: Test.
          command: |
            venv/bin/python ./bin/run_tests.py

workflows:
  version: 2
  all-tests:
    jobs:
      - osx-python2
      - osx-python3
      - linux-python2
      - linux-python3
